name: Prepare Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Prepare Release
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'Prod' || 'Dev' }}
    permissions:
      contents: write
      pull-requests: write
      packages: write
      deployments: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run compile
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}

      - name: Create Release Pull Request or Publish to VSCode Marketplace
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run changeset:publish
          title: "chore: release package"
          commit: "chore: release package"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_PAT || secrets.GITHUB_TOKEN }}
          # VSCode Marketplace token for publishing extensions
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          # OAuth Client ID for the extension (environment-specific)
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
